workerman:
    servers:
        - name: 'Symfony webserver'
          listen: http://0.0.0.0:8080
          processes: 4

    reload_strategy:
        exception:
            active: true

        file_monitor:
            active: false
